=== mwait/XsdSimple/src/main/resources/Client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wait.com/client"
	xmlns:tns="http://www.wait.com/client" elementFormDefault="qualified">
	<element name="client" type="tns:Client" />

	<complexType name="Client">
		<!-- wszystkie elementy musza sie pojawic w dokladnie takiej kolejnosci -->
		<sequence>
			<element name="id" type="tns:ID" />
			<element name="name" type="tns:String20" />
			<element name="age" type="int" />
			<element name="dob" type="date" />
			<element name="email" type="string" />
			<element name="gender" type="tns:Gender" />
			<element name="payment" type="tns:PaymentType" />
		</sequence>
	</complexType>

	<complexType name="PaymentType">
		<!--przynajmniej jeden element -->
		<choice>
			<element name="cash" type="int" />
			<element name="insurance" type="tns:Insurance" />
		</choice>
	</complexType>

	<complexType name="Insurance">
		<!-- Wszystkie musza sie pojawic, kolejnosc nie istotna -->
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>
	</complexType>

	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="String20">
		<restriction base="string">
			<maxLength value="20" />
		</restriction>
	</simpleType>

	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>

</schema>

=== mwait/XsdSimple/src/main/resources/Client.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:client xmlns:tns="http://www.wait.com/client" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wait.com/client Client.xsd ">
  <tns:id>1</tns:id>
  <tns:name>Mark</tns:name>
  <tns:age>30</tns:age>
  <tns:dob>2001-01-01</tns:dob>
  <tns:email>m@m.pl</tns:email>
  <tns:gender>M</tns:gender>
  <tns:payment>
    <tns:cash>100</tns:cash>
  </tns:payment>
</tns:client>
